name: Build Reminder App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROIDSDK: ${{ github.workspace }}/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/android-ndk
      ANDROIDAPI: 33
      ANDROIDMINAPI: 21
      BUILDOZER_ALLOW_ROOT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Upgrade pip & install essential packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo apt-get update
        sudo apt-get install -y python3-distutils openjdk-17-jdk unzip wget zip

    - name: Install Buildozer, Kivy & P4A
      run: |
        python -m pip install cython==0.29.34
        python -m pip install "kivy==2.2.1"
        python -m pip install "buildozer==1.4.0" python-for-android

    - name: Setup Android SDK & NDK
      run: |
        mkdir -p $ANDROIDSDK $ANDROIDNDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROIDSDK
        mkdir -p $ANDROIDSDK/cmdline-tools
        mv $ANDROIDSDK/cmdline-tools/* $ANDROIDSDK/cmdline-tools/latest
        yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK --licenses
        $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK "platforms;android-33" "platform-tools" "build-tools;33.0.2"

    - name: Build APK
      run: |
        buildozer android debug
