- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: 3.10  # Use Python 3.10 for Buildozer compatibility

- name: Install system dependencies
  run: |
    sudo apt-get update
    sudo apt-get install -y python3.10-venv python3.10-distutils \
        build-essential git wget unzip openjdk-11-jdk \
        python3-pip python3-setuptools python3-wheel

- name: Create virtualenv
  run: |
    python3.10 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip setuptools wheel
    pip install cython==0.29.34 buildozer==1.4.0
