name: Build ReminderApp APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROIDNDK_ROOT: ${{ github.workspace }}/android-ndk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-ndk:$PATH

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          python -m pip install cython==0.29.34
          python -m pip install "kivy==2.2.1"
          python -m pip install "buildozer==1.4.0" python-for-android distutils

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $ANDROIDSDK_ROOT/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d $ANDROIDSDK_ROOT/cmdline-tools
          mv $ANDROIDSDK_ROOT/cmdline-tools/cmdline-tools $ANDROIDSDK_ROOT/cmdline-tools/latest
          yes | $ANDROIDSDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROIDSDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          # Install NDK for python-for-android
          curl -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip ndk.zip -d $ANDROIDNDK_ROOT

      - name: Run Buildozer
        run: |
          python -m buildozer android debug
